import { Contact, EmergencyContact } from './types';

export const INITIAL_CONTACTS: Contact[] = [
  // --- REPAIR & MAINTENANCE SERVICES ---
  {
    id: 'rep-1',
    name: 'Sharma Plumbing Solutions (Rajesh)',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    category: 'repair',
    subcategory: 'Plumber',
    rating: 4.8,
    ratingsCount: 34,
    endorsements: 18,
    address: 'Shop 12, Market Complex Sector-4',
    distance: '0.6 km',
    isVerified: true,
    hours: '9:00 AM - 8:00 PM',
    whatsappEnabled: true,
    details: 'Expert in leak fixing, bathroom fitting renovations, and high pressure pump installation.',
    reviews: [
      { id: 'rev-1-1', author: 'Anil Mehta', flat: 'A-402', rating: 5, comment: 'Fixed a major sink leak in 15 mins. Highly recommended!', date: 'June 5, 2026' },
      { id: 'rev-1-2', author: 'Priya Sen', flat: 'C-104', rating: 4, comment: 'Punctual and charged the standard rate. Very professional.', date: 'May 28, 2026' }
    ]
  },
  {
    id: 'rep-2',
    name: 'Verma Electricals (Sunil)',
    phone: '+91 98123 45678',
    whatsapp: '+91 98123 45678',
    category: 'repair',
    subcategory: 'Electrician',
    rating: 4.6,
    ratingsCount: 22,
    endorsements: 12,
    address: 'Vikas Nagar Pocket-B',
    distance: '1.2 km',
    isVerified: true,
    hours: '8:00 AM - 9:00 PM',
    whatsappEnabled: true,
    details: 'Inverter setups, short circuits, fan repairs, and house wiring wizard.',
    reviews: [
      { id: 'rev-2-1', author: 'Karan Johar', flat: 'E-901', rating: 5, comment: 'Restored power at midnight. Absolute lifesaver!', date: 'June 2, 2026' }
    ]
  },
  {
    id: 'rep-3',
    name: 'Classic Carpentry (Jagdish)',
    phone: '+91 98877 66554',
    category: 'repair',
    subcategory: 'Carpenter',
    rating: 4.3,
    ratingsCount: 15,
    endorsements: 6,
    address: 'Opposite Metro Station Lane 2',
    distance: '1.8 km',
    isVerified: false,
    hours: '10:00 AM - 7:30 PM',
    whatsappEnabled: false,
    details: 'Door fittings, sunmica woodwork, sofa repair, furniture custom assembly.',
    reviews: [
      { id: 'rev-3-1', author: 'Sneha Rao', flat: 'B-708', rating: 4, comment: 'Good woodwork for kitchen cabinets, but takes his time.', date: 'May 15, 2026' }
    ]
  },
  {
    id: 'rep-4',
    name: 'QuickCool Appliance Service (Manish)',
    phone: '+91 95432 10987',
    whatsapp: '+91 95432 10987',
    category: 'repair',
    subcategory: 'Appliance Repair',
    rating: 4.7,
    ratingsCount: 41,
    endorsements: 25,
    address: 'Sardar Market Lane 1',
    distance: '0.8 km',
    isVerified: true,
    hours: '9:00 AM - 9:00 PM',
    whatsappEnabled: true,
    details: 'Specialist in AC servicing, PCB repairs, washing machines, and refrigerator gas refilling.',
    reviews: [
      { id: 'rev-4-1', author: 'Rohan Joshi', flat: 'Tower D-302', rating: 5, comment: 'Serviced my AC perfectly. It filters cold air instantly now.', date: 'June 8, 2026' },
      { id: 'rev-4-2', author: 'Neha Kapoor', flat: 'Tower B-1102', rating: 4.5, comment: 'Honest pricing. Diagnosed washing machine drum problem quickly.', date: 'June 4, 2026' }
    ]
  },
  {
    id: 'rep-5',
    name: 'PestAway Safe Controls',
    phone: '+91 90011 22334',
    category: 'repair',
    subcategory: 'Pest Control',
    rating: 4.5,
    ratingsCount: 19,
    endorsements: 9,
    address: 'Main Chowk Road Block C',
    distance: '2.1 km',
    isVerified: true,
    hours: '8:00 AM - 6:00 PM',
    whatsappEnabled: false,
    details: 'Odourless herbal gel treatments for cockroaches, bedbugs & anti-termite operations.',
    reviews: [
      { id: 'rev-5-1', author: 'Arjun Dev', flat: 'Block F-203', rating: 5, comment: 'Cockroach infestation fully cleared with safe herbal gel.', date: 'May 20, 2026' }
    ]
  },
  {
    id: 'rep-6',
    name: 'Sardar Gas Stove & LPG Service',
    phone: '+91 91234 56789',
    category: 'repair',
    subcategory: 'Gas & LPG Repair',
    rating: 4.4,
    ratingsCount: 11,
    endorsements: 5,
    address: 'Local Shanti Nagar Market',
    distance: '0.5 km',
    isVerified: true,
    hours: '9:00 AM - 8:00 PM',
    whatsappEnabled: false,
    details: 'Dealing with stove repairs, yellow flame issues, gas pipe assembly, and regulator checks.',
    reviews: []
  },

  // --- DAILY ESSENTIALS & SHOPS ---
  {
    id: 'day-1',
    name: 'Fresh Basket Supermarket',
    phone: '+91 99998 88877',
    whatsapp: '+91 99998 88877',
    category: 'daily',
    subcategory: 'Grocery Shop',
    rating: 4.7,
    ratingsCount: 122,
    endorsements: 74,
    address: 'Ground Floor, Galleria Mall Complex',
    distance: '0.3 km',
    isVerified: true,
    hours: '7:30 AM - 10:00 PM',
    whatsappEnabled: true,
    details: 'Wide range of fresh veggies, spices, daily groceries, and organic products. Free home delivery above ₹300.',
    reviews: [
      { id: 'rev-d1-1', author: 'Meera Deshmukh', flat: 'A-203', rating: 5, comment: 'Unbelievably fast home delivery. Veggies are always top fresh!', date: 'June 9, 2026' }
    ]
  },
  {
    id: 'day-2',
    name: 'Apex Medicos & Pharmacy (24/7)',
    phone: '+91 98888 77777',
    whatsapp: '+91 98888 77777',
    category: 'daily',
    subcategory: 'Medical/Pharmacy Store',
    rating: 4.9,
    ratingsCount: 164,
    endorsements: 112,
    address: 'Appasamy Road, Behind Police Station',
    distance: '0.4 km',
    isVerified: true,
    hours: '24 Hours Open',
    whatsappEnabled: true,
    details: 'Full range of prescription medicines, baby care products, health tests, and emergency oxygen. They deliver meds on WhatsApp order.',
    reviews: [
      { id: 'rev-d2-1', author: 'Dr. Nair', flat: 'Tower C-602', rating: 5, comment: 'Always stocked. Extremely helpful during emergency nighttime prescriptions.', date: 'June 7, 2026' }
    ]
  },
  {
    id: 'day-3',
    name: 'Krishna Dairy & Milk Supply',
    phone: '+91 97776 55544',
    category: 'daily',
    subcategory: 'Dairy & Milk Supply',
    rating: 4.6,
    ratingsCount: 38,
    endorsements: 20,
    address: 'Inside Shopping Gate 2, Skyline Towers',
    distance: '0.1 km',
    isVerified: true,
    hours: '6:00 AM - 12:00 PM, 4:00 PM - 9:00 PM',
    whatsappEnabled: false,
    details: 'Fresh cow milk, thick buffalo curd, freshly made Paneer, butter, and ghee delivered to doorsteps directly before 7:00 AM.',
    reviews: [
      { id: 'rev-d3-1', author: 'Sonal Jain', flat: 'D-102', rating: 4.8, comment: 'Best paneer in this entire locality. Soft and pure.', date: 'June 3, 2026' }
    ]
  },
  {
    id: 'day-4',
    name: 'A-One Bakers & Confectioners',
    phone: '+91 96667 88899',
    category: 'daily',
    subcategory: 'Bakery',
    rating: 4.4,
    ratingsCount: 29,
    endorsements: 14,
    address: 'Sector 5 High Street',
    distance: '1.1 km',
    isVerified: false,
    hours: '8:30 AM - 9:30 PM',
    whatsappEnabled: false,
    details: 'Freshly baked multigrain bread, customised birthday cakes, pastries, tea rusks, and dry snacks.',
    reviews: []
  },
  {
    id: 'day-5',
    name: 'Ramu Kaka Green Vegetables',
    phone: '+91 95554 33221',
    category: 'daily',
    subcategory: 'Vegetable Vendor',
    rating: 4.5,
    ratingsCount: 52,
    endorsements: 31,
    address: 'Street Vendor, Near Society West Gate',
    distance: '0.1 km',
    isVerified: true,
    hours: '7:00 AM - 1:00 PM, 5:00 PM - 9:00 PM',
    whatsappEnabled: false,
    details: 'Directly sourced seasonal vegetables and exotic fruits. Cheap price and fair weights.',
    reviews: [
      { id: 'rev-d5-1', author: 'Usha Devi', flat: 'Block B-001', rating: 5, comment: 'Ramu kaka always gives some coriander & green chillies for free! Very sweet man.', date: 'May 31, 2026' }
    ]
  },

  // --- HOME & PERSONAL SERVICES ---
  {
    id: 'per-1',
    name: 'Mirror & Shears Parlour (Divya)',
    phone: '+91 94441 22334',
    whatsapp: '+91 94441 22334',
    category: 'personal',
    subcategory: 'Beauty Parlour',
    rating: 4.7,
    ratingsCount: 56,
    endorsements: 28,
    address: 'Vikas Arcade, Block E, Shop 3',
    distance: '0.7 km',
    isVerified: true,
    hours: '10:00 AM - 8:00 PM (Tuesday Closed)',
    whatsappEnabled: true,
    details: 'Specialized women facial treatments, herbal hair spa, bridal makeup, wax, and nail art. Home service available on request!',
    reviews: [
      { id: 'rev-p1-1', author: 'Nalini Iyer', flat: 'Tower B-1504', rating: 5, comment: 'Fantastic home threading and hair spa. Divya takes absolute care.', date: 'June 6, 2026' }
    ]
  },
  {
    id: 'per-2',
    name: 'Elite Barber Shop (Suresh)',
    phone: '+91 93333 44455',
    category: 'personal',
    subcategory: 'Barber',
    rating: 4.4,
    ratingsCount: 42,
    endorsements: 15,
    address: 'Local Main Road, Next to Post Office',
    distance: '0.8 km',
    isVerified: true,
    hours: '9:00 AM - 9:00 PM',
    whatsappEnabled: false,
    details: 'Modern hair styling, safety razor shaves, oil head massages, kids haircuts, and beard trims. Fully air-conditioned.',
    reviews: []
  },
  {
    id: 'per-3',
    name: 'Superspeed Dry Cleaners & Laundry',
    phone: '+91 92222 33344',
    whatsapp: '+91 92222 33344',
    category: 'personal',
    subcategory: 'Laundry & Dhobi',
    rating: 4.5,
    ratingsCount: 65,
    endorsements: 33,
    address: 'Basement, Galleria Market Lane G',
    distance: '0.4 km',
    isVerified: true,
    hours: '8:30 AM - 8:30 PM',
    whatsappEnabled: true,
    details: 'Premium steam ironing, dry cleaning, detergent laundry washes, and free bulk pickup/drop inside our society.',
    reviews: [
      { id: 'rev-p3-1', author: 'Vikram Seth', flat: 'C-702', rating: 5, comment: 'Excellent steam ironing. Clothes look crisp as new.', date: 'May 25, 2026' }
    ]
  },
  {
    id: 'per-4',
    name: 'A-1 Sparkle Car Wash & Detailing',
    phone: '+91 91111 22233',
    whatsapp: '+91 91111 22233',
    category: 'personal',
    subcategory: 'Car Wash',
    rating: 4.6,
    ratingsCount: 29,
    endorsements: 19,
    address: 'Skyline Society Basement parking area',
    distance: '0.0 km',
    isVerified: true,
    hours: '6:00 AM - 10:30 AM (Daily)',
    whatsappEnabled: true,
    details: 'Early morning standard dusty car wipe-downs, interior vacuuming, tire polishing, and dashboard gloss treatments directly in your parking bay.',
    reviews: [
      { id: 'rev-p4-1', author: 'Gaurav Khanna', flat: 'A-1002', rating: 4.8, comment: 'Saves so much time! He washes my SUV inside the basement at sunrise.', date: 'June 4, 2026' }
    ]
  },
  {
    id: 'per-5',
    name: 'Gupta Raddiwala & Scrap Buyer',
    phone: '+91 90000 11122',
    category: 'personal',
    subcategory: 'Raddiwala (Scrap)',
    rating: 4.3,
    ratingsCount: 18,
    endorsements: 10,
    address: 'Visits Society Entrance Gate on Wednesdays & Sundays',
    distance: '0.1 km',
    isVerified: true,
    hours: '9:00 AM - 3:00 PM',
    whatsappEnabled: false,
    details: 'Buys old newspapers, corrugated boxes, rusted iron rods, broken plastics, and redundant dry batteries with electronic scaling.',
    reviews: [
      { id: 'rev-p5-1', author: 'Swati K.', flat: 'Block E-102', rating: 4, comment: 'Fair scales and quick collection. Much better than storing heavy cartons.', date: 'May 10, 2026' }
    ]
  },
  {
    id: 'per-6',
    name: 'Kamla Bai Domestic Help Services',
    phone: '+91 98234 56781',
    category: 'personal',
    subcategory: 'Home Helpers',
    rating: 4.7,
    ratingsCount: 38,
    endorsements: 24,
    address: 'Local Staff Stand, Gate 2',
    distance: '0.2 km',
    isVerified: true,
    hours: '7:30 AM - 5:00 PM',
    whatsappEnabled: false,
    details: 'Trusted maid and housekeeping cook. Cleans dishes, dusts flats, and preps delicious local home style food.',
    reviews: [
      { id: 'rev-p6-1', author: 'Aditi Shah', flat: 'Tower B-1402', rating: 5, comment: 'Very reliable and cooks amazing Maharashtrian dishes. Punctual!', date: 'June 4, 2026' }
    ]
  },
  {
    id: 'per-7',
    name: 'Manoj Caretaking & Dusting Desk',
    phone: '+91 97654 32109',
    category: 'personal',
    subcategory: 'Home Helpers',
    rating: 4.5,
    ratingsCount: 16,
    endorsements: 8,
    address: 'Sector-4 Main Square',
    distance: '0.8 km',
    isVerified: true,
    hours: '8:00 AM - 6:00 PM',
    whatsappEnabled: false,
    details: 'Full-time sweeping, flat cleaning, and deep dusting helper. Verified structural background.',
    reviews: []
  },
  {
    id: 'per-8',
    name: 'Paws & Whiskers Grooming (Dr. Alok)',
    phone: '+91 98877 22110',
    category: 'personal',
    subcategory: 'Pet Care',
    rating: 4.9,
    ratingsCount: 26,
    endorsements: 17,
    address: 'Shop 8, Sector-4 Market Plaza',
    distance: '0.6 km',
    isVerified: true,
    hours: '10:00 AM - 8:30 PM',
    whatsapp: '+91 98877 22110',
    whatsappEnabled: true,
    details: 'Professional dog walker, pet bathing & grooming spa, and basic health consultancy right in your society flat.',
    reviews: [
      { id: 'rev-p8-1', author: 'Ravi Teja', flat: 'Tower C-404', rating: 5, comment: 'Our Golden Retriever loves Dr. Alok! Fantastic grooming spa.', date: 'May 28, 2026' }
    ]
  },
  {
    id: 'per-9',
    name: 'Happy Tail Pet Boarding Desk',
    phone: '+91 95432 98765',
    category: 'personal',
    subcategory: 'Pet Care',
    rating: 4.8,
    ratingsCount: 19,
    endorsements: 12,
    address: 'Green Meadows Farmhouse Lane',
    distance: '2.5 km',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: 'Safe home boarding and daycare shelter for dogs and cats. Active garden playing zones, veterinary backup, and daily photo updates.',
    reviews: []
  },

  // --- NEARBY INFRASTRUCTURE / PLACES ---
  {
    id: 'ins-1',
    name: 'State Bank of India ATM',
    phone: '1800 123 4567',
    category: 'nearby',
    subcategory: 'ATM',
    rating: 4.2,
    ratingsCount: 88,
    endorsements: 45,
    address: 'Just outside Shanti Towers Gate 1',
    distance: '0.1 km',
    isVerified: true,
    hours: '24 Hours Open',
    whatsappEnabled: false,
    details: 'Equipped with cash withdrawal and statement printing. Guards are always present.',
    reviews: []
  },
  {
    id: 'ins-2',
    name: 'Sector-4 Post Office & Speed Post',
    phone: '011-2345678',
    category: 'nearby',
    subcategory: 'Post Office',
    rating: 4.0,
    ratingsCount: 37,
    endorsements: 12,
    address: 'Post Office Road, Block C Sector 4',
    distance: '0.9 km',
    isVerified: true,
    hours: '9:00 AM - 4:00 PM (Sunday Closed)',
    whatsappEnabled: false,
    details: 'Send letters, reliable speed posts, parcel bookings, savings certificates, and stamps collection.',
    reviews: []
  },
  {
    id: 'ins-4',
    name: 'Main Public Green Park',
    phone: 'N/A',
    category: 'nearby',
    subcategory: 'Parks & Recreation',
    rating: 4.8,
    ratingsCount: 155,
    endorsements: 95,
    address: 'Opposite Society Main Tower Road',
    distance: '0.2 km',
    isVerified: true,
    hours: '5:00 AM - 10:00 PM',
    whatsappEnabled: false,
    details: 'Equipped with clay jogging track, kids play sliders, open air gymnasium, clean toilets, and lush lawns.',
    reviews: [
      { id: 'rev-i4-1', author: 'Grandpa Som', flat: 'A-102', rating: 5, comment: 'Extremely peaceful at dawn. Benches are clean and lawns are manicured nicely.', date: 'May 29, 2026' }
    ]
  },
  {
    id: 'ins-5',
    name: 'Sector 4 Metro & Bus Terminus',
    phone: 'N/A',
    category: 'nearby',
    subcategory: 'Transport Hub',
    rating: 4.5,
    ratingsCount: 210,
    endorsements: 140,
    address: 'Metro Station Plaza Line-3 (Blue)',
    distance: '1.4 km',
    isVerified: true,
    hours: '6:00 AM - 11:30 PM',
    whatsappEnabled: false,
    details: 'Direct rapid transit connection to downtown, autorickshaw sharing stand on outer bay, and regular DTC bus stops.',
    reviews: []
  },
  {
    id: 'emg-1',
    name: 'Police Emergency Helpline (112)',
    phone: '112',
    category: 'emergency',
    subcategory: 'Police',
    rating: 5.0,
    ratingsCount: 1,
    endorsements: 20,
    address: 'National Central Safety Desk Command',
    distance: 'Global',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: 'National emergency standard line for immediate safety & rescue.',
    reviews: []
  },
  {
    id: 'emg-2',
    name: 'Sector-4 Police Station (Direct)',
    phone: '+91 11 2987 6543',
    category: 'emergency',
    subcategory: 'Police',
    rating: 4.5,
    ratingsCount: 12,
    endorsements: 8,
    address: 'Sector 4 Junction Chowk Post',
    distance: '1.1 km',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: 'Direct desk line of the nearest police post at Sector 4 junction.',
    reviews: []
  },
  {
    id: 'emg-3',
    name: 'City Ambulance Core Hotline',
    phone: '102',
    category: 'emergency',
    subcategory: 'Hospital',
    rating: 4.9,
    ratingsCount: 45,
    endorsements: 28,
    address: 'City Medical Command Center',
    distance: 'Global',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: 'Primary rapid medical dispatch command desk for cardiac & trauma care.',
    reviews: []
  },
  {
    id: 'emg-4',
    name: 'Fortis Emergency Trauma Center',
    phone: '+91 11 4112 1102',
    category: 'emergency',
    subcategory: 'Hospital',
    rating: 4.7,
    ratingsCount: 38,
    endorsements: 19,
    address: 'Vasant Kunj Main Hospital Wing',
    distance: '2.4 km',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: 'Fully equipped critical care unit, trauma surgeons and ICU. 24/7.',
    reviews: []
  },
  {
    id: 'emg-5',
    name: 'Fire Brigade Headquarters Desk',
    phone: '101',
    category: 'emergency',
    subcategory: 'Fire Brigade',
    rating: 5.0,
    ratingsCount: 3,
    endorsements: 15,
    address: 'District Fire Station 2',
    distance: '4.2 km',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: 'Rapid response fire protection, engine dispatch and gas emergencies.',
    reviews: []
  },
  {
    id: 'emg-9',
    name: "National Women's Helpline Desk (1091)",
    phone: '1091',
    category: 'emergency',
    subcategory: "Women's Helpline",
    rating: 5.0,
    ratingsCount: 18,
    endorsements: 15,
    address: 'National Safety Division Desk',
    distance: 'Global',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: '24/7 National emergency safety support, immediate assistance and counseling for women.',
    reviews: []
  },
  {
    id: 'emg-10',
    name: 'National Child Safety Helpline Desk (1098)',
    phone: '1098',
    category: 'emergency',
    subcategory: "Child Helpline",
    rating: 5.0,
    ratingsCount: 22,
    endorsements: 19,
    address: 'National Child Welfare Division',
    distance: 'Global',
    isVerified: true,
    hours: '24 Hours',
    whatsappEnabled: false,
    details: '24-hour toll-free emergency phone service for children and youth in distress or need.',
    reviews: []
  }
];

export const EMERGENCY_CONTACTS: EmergencyContact[] = [];

// Keywords mapping to simplify search
export const SEARCH_KEYWORDS: { [key: string]: string[] } = {
  // mapped key -> subcategories
  'leak': ['Plumber'],
  'tap': ['Plumber'],
  'sink': ['Plumber'],
  'pipe': ['Plumber'],
  'clog': ['Plumber'],
  'washbasin': ['Plumber'],
  'drain': ['Plumber'],
  'plumbing': ['Plumber'],
  'fuse': ['Electrician'],
  'wire': ['Electrician'],
  'short': ['Electrician'],
  'power': ['Electrician', 'Power Grid Grid Outage Desk'],
  'electricity': ['Electrician'],
  'fan': ['Electrician', 'Appliance Repair'],
  'bulb': ['Electrician'],
  'light': ['Electrician'],
  'invertor': ['Electrician'],
  'switch': ['Electrician'],
  'door': ['Carpenter'],
  'table': ['Carpenter'],
  'chair': ['Carpenter'],
  'wooden': ['Carpenter'],
  'cabinet': ['Carpenter'],
  'bed': ['Carpenter'],
  'sofa': ['Carpenter'],
  'ac': ['Appliance Repair'],
  'cooler': ['Appliance Repair'],
  'fridge': ['Appliance Repair'],
  'refrigerator': ['Appliance Repair'],
  'washing': ['Appliance Repair'],
  'oven': ['Appliance Repair'],
  'microwave': ['Appliance Repair'],
  'technician': ['Appliance Repair'],
  'pest': ['Pest Control'],
  'termite': ['Pest Control'],
  'insect': ['Pest Control'],
  'cockroach': ['Pest Control'],
  'ant': ['Pest Control'],
  'bug': ['Pest Control'],
  'gas': ['Gas & LPG Repair', 'Water Tanker Society Supply Desk'],
  'stove': ['Gas & LPG Repair'],
  'cylinder': ['Gas & LPG Repair'],
  'oil': ['Gas & LPG Repair'],
  'lpg': ['Gas & LPG Repair'],
  
  'grocery': ['Grocery Shop'],
  'rice': ['Grocery Shop'],
  'wheat': ['Grocery Shop'],
  'oil-grocery': ['Grocery Shop'],
  'shop': ['Grocery Shop', 'Medical/Pharmacy Store'],
  'supermarket': ['Grocery Shop'],
  'veggie': ['Vegetable Vendor', 'Grocery Shop'],
  'vegetable': ['Vegetable Vendor'],
  'fruit': ['Vegetable Vendor', 'Grocery Shop'],
  'onion': ['Vegetable Vendor'],
  'potato': ['Vegetable Vendor'],
  'medicine': ['Medical/Pharmacy Store'],
  'pill': ['Medical/Pharmacy Store'],
  'tablet': ['Medical/Pharmacy Store'],
  'chemist': ['Medical/Pharmacy Store'],
  'pharmacy': ['Medical/Pharmacy Store'],
  'medical': ['Medical/Pharmacy Store'],
  'bandage': ['Medical/Pharmacy Store'],
  'milk': ['Dairy & Milk Supply'],
  'curd': ['Dairy & Milk Supply'],
  'paneer': ['Dairy & Milk Supply'],
  'butter': ['Dairy & Milk Supply'],
  'dairy': ['Dairy & Milk Supply'],
  'bread': ['Bakery'],
  'cake': ['Bakery'],
  'bakery': ['Bakery'],
  'biscuit': ['Bakery'],
  'rusk': ['Bakery'],
  'pastry': ['Bakery'],

  'parlour': ['Beauty Parlour'],
  'salon': ['Beauty Parlour', 'Barber'],
  'hair': ['Beauty Parlour', 'Barber'],
  'facial': ['Beauty Parlour'],
  'makeup': ['Beauty Parlour'],
  'shave': ['Barber'],
  'trim': ['Barber'],
  'barber': ['Barber'],
  'laundry': ['Laundry & Dhobi'],
  'dhobi': ['Laundry & Dhobi'],
  'iron': ['Laundry & Dhobi'],
  'wash': ['Laundry & Dhobi', 'Car Wash'],
  'dry': ['Laundry & Dhobi'],
  'clean': ['Laundry & Dhobi', 'Car Wash'],
  'car': ['Car Wash'],
  'scrap': ['Raddiwala (Scrap)'],
  'newspaper': ['Raddiwala (Scrap)'],
  'raddi': ['Raddiwala (Scrap)'],
  'bottle': ['Raddiwala (Scrap)'],
  'paper': ['Raddiwala (Scrap)'],
  'maid': ['Maid & Housekeeping', 'Home Helpers'],
  'cook': ['Home Helpers'],
  'helper': ['Home Helpers'],
  'pet': ['Pet Care'],
  'dog': ['Pet Care'],
  'cat': ['Pet Care'],
  'grooming': ['Pet Care'],
  'animal': ['Pet Care'],

  'atm': ['ATM'],
  'cash': ['ATM'],
  'bank': ['ATM'],
  'money': ['ATM'],
  'post': ['Post Office'],
  'letter': ['Post Office'],
  'speed': ['Post Office'],
  'park': ['Parks & Recreation'],
  'walk': ['Parks & Recreation'],
  'green': ['Parks & Recreation'],
  'play': ['Parks & Recreation'],
  'gym': ['Parks & Recreation'],
  'metro': ['Transport Hub'],
  'bus': ['Transport Hub'],
  'train': ['Transport Hub'],
  'transit': ['Transport Hub'],
  'station': ['Transport Hub'],
  'auto': ['Transport Hub'],

  'police': ['Police'],
  'cop': ['Police'],
  'safety': ['Police'],
  'thief': ['Police'],
  'hospital': ['Hospital'],
  'doctor': ['Hospital'],
  'accident': ['Hospital'],
  'ambulance': ['Hospital'],
  'fire': ['Fire Brigade'],
  'smoke': ['Fire Brigade'],
  'women': ["Women's Helpline"],
  'child': ["Child Helpline"],
  'kids': ["Child Helpline"],
  'abuse': ["Women's Helpline"]
};
